# Computo de Alto Desempeño
### Roberto Guerrero Bueno (rguerrero.mca16@lania.edu.mx)

In [15]:
import time
import numpy as np
import ipyparallel as ipp
%matplotlib inline

In [16]:
c = ipp.Client()
c.ids

[0, 1, 2, 3]

In [18]:
#Acceder a motores especificos
c[0:2]
c[1:3]

<DirectView [1, 2]>

In [19]:
#aply aplica una funcion con los motores especificados
c[1:3].apply_sync(lambda: "Hola clase de MCA")

['Hola clase de MCA', 'Hola clase de MCA']

In [7]:
#Definimos una funcion que determina si un numero dado es primo:
PrimeQ=lambda x: all(x % i != 0 for i in range(int(x**0.5)+1)[2:]) and x>1

In [25]:
#apply_sync aplica la funcion para cada motor
#map_sync divide una funcion en todos los motores
c[:].map_sync(lambda x,y,z: x+y+z,range(10),range(10),range(10))
c[:].apply_sync(lambda x,y,z: x+y+z,range(10),range(10),range(10))

[[0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9],
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9],
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9],
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9]]

In [35]:
x = 2**13
np.arange(int(x**0.5)+1) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90])

In [42]:
%%timeit
x = 2**30
for i in np.arange(int(x**0.5)+1)[2:]:
    x % i

#hacer una grafica modicando el valor de x = 2**n de 1 hasta donde se pueda

10 loops, best of 3: 20.5 ms per loop


In [40]:
all?

In [52]:
def PrimeQ0(x):
    import numpy as np
    return all(x % i for i in np.arange(int(x**0.5)+1)[2:])

In [48]:
PrimeQ0(2**7)

False

In [44]:
PrimeQ = lambda x: all(x % i != 0 for i in np.arange(int(x**0.5)+1)[2:]) and x>1

In [54]:
#c[0].apply_sync(PrimeQ0,2**7)
c[:].apply_sync(PrimeQ0,2**7)

[False, False, False, False]

In [55]:
dview = c[:]

In [56]:
dview.apply_sync?

In [57]:
dview.map_sync?

In [58]:
2**np.arange(7)

array([ 1,  2,  4,  8, 16, 32, 64])

In [64]:
%timeit dview.map_sync(PrimeQ0,2**np.arange(30))
#Hacer una grafica con esta funcion

10 loops, best of 3: 100 ms per loop


In [66]:
%%timeit
for i in 2**np.arange(30):
    x % i

10000 loops, best of 3: 44.1 µs per loop


In [69]:
np.all(np.array([x % i for i in np.arange(int(x**0.5)+1)[2:]]))

False

In [72]:
def PrimeQ1(x):
    import numpy as np
    return np.all(np.array([x % i for i in np.arange(np.int(x**0.5)+1)[2:]]))

In [73]:
%timeit dview.map_sync(PrimeQ1,2**np.arange(25))

10 loops, best of 3: 117 ms per loop


In [74]:
np.mod?

In [75]:
np.mod(24,12)

0

In [76]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [78]:
np.mod(np.arange(24),12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11])

In [79]:
np.array([hora % 12 for hora in np.arange(24)])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11])

In [84]:
for med in np.arange(12,20):
    print np.mod(np.arange(24),med)

[ 0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12  0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13  0  1  2  3  4  5  6  7  8  9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14  0  1  2  3  4  5  6  7  8]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16  0  1  2  3  4  5  6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17  0  1  2  3  4  5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18  0  1  2  3  4]


In [85]:
np.arange(np.int(x**0.5)+1)[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90])

In [88]:
def PrimeQ2(x):
    import numpy as np
    lista = np.arange(np.int(x**0.5)+1)[2:]
    residuos = np.mod(x,lista)
    return np.all(residuos)

In [89]:
#Grafica con esta instruccion respecto a PrimeQ0,1,2
dview.map_sync(PrimeQ2,2**np.arange(10))

[True, True, False, False, False, False, False, False, False, False]

In [90]:
dview.map_sync(PrimeQ1,2**np.arange(10))

[True, True, False, False, False, False, False, False, False, False]